FROM alpine:latest

# Install dependencies
RUN apk update \
 && apk upgrade \
 && apk add openjdk11-jre-headless

# Install app
WORKDIR /app
COPY build/lib/* /app/lib/
COPY build/*-runner.jar /app/application.jar

EXPOSE 3200

CMD ["java", "-jar", "application.jar"]
