FROM alpine:3.13

# Install app
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root build/*-runner /work/application

EXPOSE 3200
USER 1001

CMD ["./application"]
