FROM alpine:edge

# Install dependencies
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
 && apk update \
 && apk upgrade \
 && apk add ffmpeg openimageio-tools

# Install app
WORKDIR /app
COPY build/*-runner /app/application

EXPOSE 3201

CMD ["./application"]
